#!/usr/bin/env bash
#
# agent-docs.sh — keep AGENTS.md / CLAUDE.md / GEMINI.md identical per directory,
# and (optionally) keep a shared-core invariants block in sync.
#
# One canonical file per directory holds the real content; the other tool names are
# symlinks to it, so Claude Code, Codex, and Gemini CLI read identical bytes. Drift
# between the three names becomes impossible by construction. A pre-commit hook runs
# `--check` so an accidental overwrite (a tool rewriting CLAUDE.md as a real file)
# fails loudly instead of rotting silently.
#
# This script is generic: it AUTO-DISCOVERS every directory that contains a real
# canonical file (default AGENTS.md) and manages the symlinks there. No per-repo
# config needed. Works for single-root and multi-root/monorepo projects.
#
# Config via environment (all optional):
#   AGENT_DOCS_CANONICAL   canonical filename (default: AGENTS.md)
#   AGENT_DOCS_LINKS       space-separated link names (default: "CLAUDE.md GEMINI.md")
#   AGENT_DOCS_SHARED      path to shared-core file (default: docs/agents/shared-core.md)
#   AGENT_DOCS_UPSTREAM    path to an upstream repo to pull shared-core from (multi-repo)
#
# Usage:
#   tools/agent-docs.sh --check                 verify symlinks (+ embedded shared-core if present)
#   tools/agent-docs.sh --sync                  (re)create symlinks + regenerate the embedded block
#   tools/agent-docs.sh --check-cross [PATH]    compare this repo's shared-core with another's
#
set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || (cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd))"
cd "$ROOT_DIR"

CANON="${AGENT_DOCS_CANONICAL:-AGENTS.md}"
read -r -a LINKS <<< "${AGENT_DOCS_LINKS:-CLAUDE.md GEMINI.md}"
SHARED="${AGENT_DOCS_SHARED:-docs/agents/shared-core.md}"
UPSTREAM="${AGENT_DOCS_UPSTREAM:-}"
BEGIN_RE='<!-- BEGIN SHARED-CORE'
END_RE='<!-- END SHARED-CORE -->'
PRUNE=( -name node_modules -o -name .git -o -name vendor -o -name build -o -name dist -o -name .dart_tool -o -name Pods )

fail=0
err() { echo "  ✗ $*" >&2; fail=1; }
ok()  { echo "  ✓ $*"; }

hash_of() { shasum -a 256 "$1" | cut -c1-12; }

# Every directory holding a REAL (non-symlink) canonical file.
discover_dirs() {
  find . \( "${PRUNE[@]}" \) -prune -o -type f -name "$CANON" -print 2>/dev/null \
    | while read -r f; do [[ -L "$f" ]] || dirname "$f"; done | sort -u
}

extract_block() {
  awk -v b="$BEGIN_RE" -v e="$END_RE" '
    $0 ~ b {grab=1; next} $0 ~ e {grab=0; next} grab {print}
  ' "$1"
}

sync_shared_from_upstream() {
  [[ -n "$UPSTREAM" ]] || return 0
  local up="$UPSTREAM/$SHARED"
  [[ -f "$up" ]] || { echo "agent-docs: upstream shared-core not found at $up" >&2; exit 2; }
  mkdir -p "$(dirname "$SHARED")"; cp -f "$up" "$SHARED"
  echo "synced shared-core from upstream ($UPSTREAM)"
}

embed_shared_core() {
  [[ -f "$SHARED" ]] || return 0
  local agents="$CANON" h begin tmp
  [[ -f "$agents" ]] || return 0
  h="$(hash_of "$SHARED")"
  begin="<!-- BEGIN SHARED-CORE hash:${h} src:${SHARED} — generated by agent-docs.sh --sync; edit ${SHARED} then re-sync -->"
  tmp="$(mktemp)"
  if grep -q "$BEGIN_RE" "$agents"; then
    awk -v b="$BEGIN_RE" '$0 ~ b {exit} {print}' "$agents" > "$tmp.head"
    awk -v e="$END_RE" 'found {print} $0 ~ e {found=1}' "$agents" > "$tmp.tail"
    { cat "$tmp.head"; printf '%s\n' "$begin"; cat "$SHARED"; printf '%s\n' "$END_RE"; cat "$tmp.tail"; } > "$tmp"
    rm -f "$tmp.head" "$tmp.tail"
  else
    { cat "$agents"; printf '\n%s\n' "$begin"; cat "$SHARED"; printf '%s\n' "$END_RE"; } > "$tmp"
  fi
  mv "$tmp" "$agents"
  echo "embedded shared-core (hash:$h) into root $CANON"
}

cmd_sync() {
  sync_shared_from_upstream
  embed_shared_core
  local d n
  while read -r d; do
    [[ -n "$d" ]] || continue
    for n in "${LINKS[@]}"; do
      ln -sf "$CANON" "$d/$n"
    done
    echo "linked $d/{$(IFS=,; echo "${LINKS[*]}")} -> $CANON"
  done < <(discover_dirs)
  echo "agent-docs: sync complete (canonical: $CANON)"
}

cmd_check() {
  echo "agent-docs: checking (canonical: $CANON)"
  local found=0 d n
  while read -r d; do
    [[ -n "$d" ]] || continue
    found=1
    for n in "${LINKS[@]}"; do
      if [[ ! -e "$d/$n" && ! -L "$d/$n" ]]; then
        err "$d/$n missing (expected symlink -> $CANON; run --sync)"
      elif [[ ! -L "$d/$n" ]]; then
        err "$d/$n is a real file, not a symlink to $CANON. A tool may have overwritten it."
      elif [[ "$(readlink "$d/$n")" != "$CANON" ]]; then
        err "$d/$n -> $(readlink "$d/$n") (expected $CANON)"
      else
        ok "$d/$n -> $CANON"
      fi
    done
  done < <(discover_dirs)
  [[ "$found" -eq 1 ]] || err "no directories with a real $CANON found — nothing is canonical yet"
  if [[ -f "$SHARED" ]]; then
    if ! grep -q "$BEGIN_RE" "$CANON" 2>/dev/null; then
      err "root $CANON has no SHARED-CORE block but $SHARED exists (run --sync)"
    elif diff -q <(extract_block "$CANON") "$SHARED" >/dev/null; then
      ok "embedded shared-core matches $SHARED (hash:$(hash_of "$SHARED"))"
    else
      err "embedded shared-core in $CANON is stale vs $SHARED (run --sync)"
    fi
  fi
  if [[ "$fail" -ne 0 ]]; then echo "agent-docs: CHECK FAILED" >&2; exit 1; fi
  echo "agent-docs: check passed"
}

cmd_check_cross() {
  local other="${1:-$UPSTREAM}"
  [[ -n "$other" ]] || { echo "agent-docs: pass the other repo path (or set AGENT_DOCS_UPSTREAM)" >&2; exit 2; }
  local of="$other/$SHARED"
  [[ -f "$SHARED" ]] || { echo "agent-docs: no local $SHARED to compare" >&2; exit 2; }
  [[ -f "$of" ]] || { echo "agent-docs: other repo shared-core not found at $of" >&2; exit 2; }
  if diff -q "$SHARED" "$of" >/dev/null; then
    echo "agent-docs: shared-core identical across repos ($(hash_of "$SHARED"))"
  else
    echo "agent-docs: SHARED-CORE DRIFT between repos:" >&2
    diff "$SHARED" "$of" >&2 || true
    exit 1
  fi
}

case "${1:-}" in
  --sync)        cmd_sync ;;
  --check)       cmd_check ;;
  --check-cross) shift; cmd_check_cross "${1:-}" ;;
  *) echo "usage: $0 --check | --sync | --check-cross [other-repo-path]" >&2; exit 2 ;;
esac
